Repository RedHatQE/must-gather-explorer, pull requests merged in 2024-09, with the labels that each got.

#6 feat: Update pre-commit config with new hook versions and repositories
  .pre-commit-config.yaml
Labels: verified, size/M, can-be-merged, branch-main, commented-coderabbitai[bot], approved-jpeimer

#4 Populate resource aliases, update README
  README.md
  app/manifests/aliases.json
  app/resource_aliases.py
Labels: verified, size/XXL, can-be-merged, branch-main, approved-myakove, commented-coderabbitai[bot]

#11 Fix poetry: add pyhelper-utils
  poetry.lock
  pyproject.toml
Labels: verified, size/XL, can-be-merged, branch-main, approved-myakove
