Repository RedHatQE/must-gather-explorer, pull requests merged in 2024-12, with the labels that each got.

#45 Use Loader=CSafeLoader to load YAMLs faster
  must_gather_explorer/main.py
Labels: verified, size/XS, can-be-merged, branch-main, approved-jpeimer

#47 Extract all logic to function
  README.md
  must_gather_explorer/main.py
  must_gather_explorer/prompt_handler.py
  must_gather_explorer/resource_aliases.py
  must_gather_explorer/utils.py
  pyproject.toml
  uv.lock
Labels: verified, size/XXL, can-be-merged, branch-main, approved-jpeimer

#52 Remove -k and --name required flags
  must_gather_explorer/prompt_handler.py
  uv.lock
Labels: verified, size/XS, can-be-merged, branch-main, approved-myakove

#54 Print specified yaml fields, like .spec.storageClassName
  README.md
  must_gather_explorer/prompt_handler.py
  must_gather_explorer/utils.py
Labels: verified, size/M, can-be-merged, branch-main, approved-myakove

#60 Remove must_gather_shell function, call call_actions direct
  must_gather_explorer/prompt_handler.py
  must_gather_explorer/utils.py
  uv.lock
Labels: verified, size/S, can-be-merged, branch-main, commented-coderabbitai[bot], approved-jpeimer

#62 Add resource info when asking for fields
  must_gather_explorer/prompt_handler.py
  must_gather_explorer/utils.py
Labels: verified, size/S, can-be-merged, branch-main, approved-jpeimer
